version: "3"
services:
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - 6379:6379

  app:
    build: ./
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
    command:
      sh -c 'node server.js'
